INSERT INTO _User (userType, blocked, deleted, name, password, username, areamanager, profile, sector, sectormanager, sectorspecialist)
VALUES
(1, FALSE, NULL, 'Sophia Anderson', 'USER', 'USER1', NULL, 1, 1, NULL, NULL),
(1, FALSE, NULL, 'Noah Johnson', 'USER', 'USER2', NULL, 1, 1, NULL, NULL),
(1, FALSE, NULL, 'Olivia Smith', 'USER', 'USER3', NULL, 1, 1, NULL, NULL),
(1, FALSE, NULL, 'Liam Brown', 'USER', 'USER4', NULL, 1, 1, NULL, NULL),
(1, FALSE, NULL, 'Emma Davis', 'USER', 'USER5', NULL, 1, 1, NULL, NULL),
(1, FALSE, NULL, 'Jackson Wilson', 'USER', 'USER6', NULL, 1, 2, NULL, NULL),
(1, FALSE, NULL, 'Ava Martinez', 'USER', 'USER7', NULL, 1, 2, NULL, NULL),
(1, FALSE, NULL, 'Lucas Taylor', 'USER', 'USER8', NULL, 1, 2, NULL, NULL),
(1, FALSE, NULL, 'Mia Clark', 'USER', 'USER9', NULL, 1, 2, NULL, NULL),
(1, FALSE, NULL, 'Aiden Thomas', 'USER', 'USER10', NULL, 1, 2, NULL, NULL),
(1, FALSE, NULL, 'Isabella White', 'USER', 'USER11', NULL, 1, 3, NULL, NULL),
(1, FALSE, NULL, 'Ethan Harris', 'USER', 'USER12', NULL, 1, 3, NULL, NULL),
(1, FALSE, NULL, 'Charlotte Jackson', 'USER', 'USER13', NULL, 1, 3, NULL, NULL),
(1, FALSE, NULL, 'Oliver Evans', 'USER', 'USER14', NULL, 1, 3, NULL, NULL),
(1, FALSE, NULL, 'Amelia Moore', 'USER', 'USER15', NULL, 1, 3, NULL, NULL);

INSERT INTO _User (userType, blocked, deleted, name, password, username, areamanager, profile, sector, sectormanager, sectorspecialist)
VALUES
(1, FALSE, NULL, 'Benjamin Lee', 'SPECIALIST', 'SPECIALIST1', NULL, 2, 1, NULL, 1),
(1, FALSE, NULL, 'Harper Hall', 'SPECIALIST', 'SPECIALIST2', NULL, 2, 1, NULL, 1),
(1, FALSE, NULL, 'Henry Wright', 'SPECIALIST', 'SPECIALIST3', NULL, 2, 1, NULL, 1),
(1, FALSE, NULL, 'Ella King', 'SPECIALIST', 'SPECIALIST4', NULL, 2, 1, NULL, 1),
(1, FALSE, NULL, 'Mason Scott', 'SPECIALIST', 'SPECIALIST5', NULL, 2, 1, NULL, 1),
(1, FALSE, NULL, 'Scarlett Turner', 'SPECIALIST', 'SPECIALIST6', NULL, 2, 2, NULL, 1),
(1, FALSE, NULL, 'William Adams', 'SPECIALIST', 'SPECIALIST7', NULL, 2, 2, NULL, 1),
(1, FALSE, NULL, 'Luna Parker', 'SPECIALIST', 'SPECIALIST8', NULL, 2, 2, NULL, 1),
(1, FALSE, NULL, 'James Rodriguez', 'SPECIALIST', 'SPECIALIST9', NULL, 2, 2, NULL, 1),
(1, FALSE, NULL, 'Chloe Martinez', 'SPECIALIST', 'SPECIALIST10', NULL, 2, 2, NULL, 1),
(1, FALSE, NULL, 'Sebastian Green', 'SPECIALIST', 'SPECIALIST11', NULL, 2, 3, NULL, 1),
(1, FALSE, NULL, 'Sophie Wilson', 'SPECIALIST', 'SPECIALIST12', NULL, 2, 3, NULL, 1),
(1, FALSE, NULL, 'Elijah Brown', 'SPECIALIST', 'SPECIALIST13', NULL, 2, 3, NULL, 1),
(1, FALSE, NULL, 'Mia Turner', 'SPECIALIST', 'SPECIALIST14', NULL, 2, 3, NULL, 1),
(1, FALSE, NULL, 'Oliver Harris', 'SPECIALIST', 'SPECIALIST15', NULL, 2, 3, NULL, 1);

-- Generar 5 jefes de sector (sectormanager) para cada sector
INSERT INTO _User (userType, blocked, deleted, name, password, username, areamanager, profile, sector, sectormanager, sectorspecialist)
VALUES
(1, FALSE, NULL, 'Lucio Paulino', 'DEVELOPMENTMANAGER', 'DEVELOPMENTMANAGER', NULL, 3, 1, 1, NULL),
(1, FALSE, NULL, 'Marcos Kanu', 'COMMUNICATIONMANAGER', 'COMMUNICATIONMANAGER', NULL, 3, 2, 2, NULL),
(1, FALSE, NULL, 'Florencio Varella', 'SUPPORTMANAGER', 'SUPPORTMANAGER', NULL, 3, 3, 3, NULL),
(1, FALSE, NULL, 'Tomas Toniut', 'MANAGER', 'MANAGER', NULL, 3, 3, NULL, NULL),
(1,FALSE,null,'AREAMANAGER', 'AREAMANAGER', 'AREAMANAGER', 1, 4, 3, NULL, NULL);

INSERT INTO Task (datelimit, description, title, category, owner, parenttask, priority, solver, state)
VALUES
('2023-10-25', 'Resolver problema de red en Development Sector', 'Problema de red en Development', (SELECT c.category FROM Category AS c WHERE c.sector = 1 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), NULL, 1),
('2023-11-15', 'Solucionar problemas de comunicación interna', 'Problemas de comunicación en Communication', (SELECT c.category FROM Category AS c WHERE c.sector = 2 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), NULL, 1),
('2023-12-08', 'Atender solicitud de soporte técnico', 'Solicitud de soporte en Support', (SELECT c.category FROM Category AS c WHERE c.sector = 3 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), NULL, 1),
('2023-11-30', 'Problemas con la base de datos en Development Sector', 'Problemas de base de datos en Development', (SELECT c.category FROM Category AS c WHERE c.sector = 1 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 1 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-12-15', 'Investigar errores en el servidor de correo', 'Errores en el servidor de correo en Communication', (SELECT c.category FROM Category AS c WHERE c.sector = 2 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 2 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-12-20', 'Atender solicitud de asistencia técnica', 'Solicitud de asistencia técnica en Support', (SELECT c.category FROM Category AS c WHERE c.sector = 3 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 3 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-11-05', 'Desarrollar nueva característica en el sitio web', 'Desarrollo de nueva característica en Development', (SELECT c.category FROM Category AS c WHERE c.sector = 1 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 1 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-10-30', 'Optimizar la infraestructura de comunicaciones', 'Optimización de infraestructura en Communication', (SELECT c.category FROM Category AS c WHERE c.sector = 2 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 2 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-11-25', 'Atender solicitud de soporte de hardware', 'Soporte de hardware en Support', (SELECT c.category FROM Category AS c WHERE c.sector = 3 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 3 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-11-12', 'Resolver problemas de seguridad en el software', 'Problemas de seguridad en Development', (SELECT c.category FROM Category AS c WHERE c.sector = 1 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), NULL, 1),
('2023-12-10', 'Mantenimiento del sistema de correo', 'Mantenimiento del sistema de correo en Communication', (SELECT c.category FROM Category AS c WHERE c.sector = 2 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 2 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-12-05', 'Atender solicitud de asistencia técnica', 'Solicitud de asistencia técnica en Support', (SELECT c.category FROM Category AS c WHERE c.sector = 3 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 3 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-11-28', 'Desarrollo de aplicaciones móviles', 'Desarrollo de aplicaciones móviles en Development', (SELECT c.category FROM Category AS c WHERE c.sector = 1 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 1 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-11-21', 'Optimización de la red de comunicaciones', 'Optimización de red de comunicaciones en Communication', (SELECT c.category FROM Category AS c WHERE c.sector = 2 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 2 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-11-22', 'Atender solicitud de soporte de software', 'Soporte de software en Support', (SELECT c.category FROM Category AS c WHERE c.sector = 3 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), NULL, 1),
('2023-11-14', 'Resolución de problemas de rendimiento', 'Problemas de rendimiento en Development', (SELECT c.category FROM Category AS c WHERE c.sector = 1 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 1 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-12-18', 'Actualización del sistema de comunicación', 'Actualización del sistema de comunicación en Communication', (SELECT c.category FROM Category AS c WHERE c.sector = 2 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 2 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-12-23', 'Atender solicitud de asistencia técnica', 'Solicitud de asistencia técnica en Support', (SELECT c.category FROM Category AS c WHERE c.sector = 3 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 3 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-10-29', 'Desarrollo de software de gestión', 'Desarrollo de software de gestión en Development', (SELECT c.category FROM Category AS c WHERE c.sector = 1 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 1 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-10-30', 'Resolución de problemas de red en Communication Sector', 'Problemas de red en Communication', (SELECT c.category FROM Category AS c WHERE c.sector = 2 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 2 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-12-13', 'Mejorar la velocidad de carga del sitio web', 'Optimización de velocidad de sitio web', (SELECT c.category FROM Category AS c WHERE c.sector = 3 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), NULL, 1),
('2023-11-17', 'Configurar un nuevo sistema de videoconferencia', 'Configuración de sistema de videoconferencia', (SELECT c.category FROM Category AS c WHERE c.sector = 1 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 1 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-12-21', 'Instalar nuevas impresoras en la oficina', 'Instalación de impresoras', (SELECT c.category FROM Category AS c WHERE c.sector = 2 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 2 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-12-05', 'Actualizar la base de datos de clientes', 'Actualización de base de datos de clientes', (SELECT c.category FROM Category AS c WHERE c.sector = 3 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), NULL, 1),
('2023-11-19', 'Investigar problemas de conectividad en la red interna', 'Problemas de conectividad en red interna', (SELECT c.category FROM Category AS c WHERE c.sector = 1 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 1 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-12-28', 'Atender solicitud de asistencia en software contable', 'Asistencia en software contable', (SELECT c.category FROM Category AS c WHERE c.sector = 2 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 2 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-11-30', 'Optimizar la infraestructura de correo electrónico', 'Optimización de infraestructura de correo', (SELECT c.category FROM Category AS c WHERE c.sector = 2 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 2 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-12-08', 'Atender solicitud de soporte en hardware de oficina', 'Soporte en hardware de oficina', (SELECT c.category FROM Category AS c WHERE c.sector = 2 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 2 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-12-02', 'Resolver problemas de seguridad en la aplicación móvil', 'Problemas de seguridad en app móvil', (SELECT c.category FROM Category AS c WHERE c.sector = 1 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), NULL, 1),
('2023-11-26', 'Mantenimiento del sistema de correo electrónico', 'Mantenimiento del sistema de correo', (SELECT c.category FROM Category AS c WHERE c.sector = 2 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 2 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
('2023-12-19', 'Atender solicitud de asistencia en software de diseño', 'Asistencia en software de diseño', (SELECT c.category FROM Category AS c WHERE c.sector = 3 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 3 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
(NULL, 'Desarrollo de software de gestión de proyectos', 'Desarrollo de software de gestión de proyectos', (SELECT c.category FROM Category AS c WHERE c.sector = 1 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), NULL, 1),
(NULL, 'Optimización de la red de comunicaciones internas', 'Optimización de red de comunicaciones internas', (SELECT c.category FROM Category AS c WHERE c.sector = 2 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 2 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
(NULL, 'Atender solicitud de soporte en software de contabilidad', 'Soporte en software de contabilidad', (SELECT c.category FROM Category AS c WHERE c.sector = 3 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 3 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
(NULL, 'Resolución de problemas de rendimiento en aplicaciones web', 'Problemas de rendimiento en aplicaciones web', (SELECT c.category FROM Category AS c WHERE c.sector = 1 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 1 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
(NULL, 'Actualización del sistema de comunicación interna', 'Actualización del sistema de comunicación interna', (SELECT c.category FROM Category AS c WHERE c.sector = 2 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u WHERE u.sectorspecialist = 2 ORDER BY RANDOM() LIMIT 1), (floor(random() * 4 + 2)::integer)),
(NULL, 'Atender solicitud de asistencia en software de recursos humanos', 'Asistencia en software de recursos humanos', (SELECT c.category FROM Category AS c WHERE c.sector = 3 ORDER BY RANDOM() LIMIT 1), (SELECT u._user FROM _User AS u ORDER BY RANDOM() LIMIT 1), NULL, (SELECT p.priority FROM Priority AS p ORDER BY RANDOM() LIMIT 1), NULL, 1);

UPDATE Sector AS s SET sectormanager = (SELECT u._user FROM _user AS u WHERE u.sectormanager = s.sector);